### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by su314ka** [TheRealLordFractal/Bip39Generator#2]
I receive below errors for 6 and 12 words. Is something that I`m doing wrong? 
Could you give the exact names of python dependencies packages? 
I install the dependencies with pip install but I don`t find all.
Thanks!

D:\Bip39Generator>generate6words.py -n 5000000 -o out.txt
  File "D:\Bip39Generator\generate6words.py", line 42
    word3 = CODEWORDS[int(random.uniform(0,len(CODEWORDS)))]
                                                           ^
TabError: inconsistent use of tabs and spaces in indentation
-----------
D:\Bip39Generator>generate12words.py -n 5000000 -o out.txt
  File "D:\Bip39Generator\generate12words.py", line 66
    except getopt.error, msg:
                       ^
SyntaxError: invalid syntax

**Comment by TheRealLordFractal** [comment]
did you try with generate12words.py ? and do you get the same message?

**Comment by su314ka** [comment]
I receive below error:

D:\Bip39Generator>generate12words.py -n 50000 -o out.txt
  File "D:\Bip39Generator\generate12words.py", line 66
    except getopt.error, msg:
                       ^
SyntaxError: invalid syntax

**Comment by TheRealLordFractal** [comment]
I have tested the error, I have fixed generate6words and generate12words, each will output corresponding file... aka 12words.txt  and 6words.txt

Let me know if you have any other issues.

**Comment by su314ka** [comment]
Same error like below. Could you please list the exact names of the  python dependencies (could be that i don`t have them all).
Maybe put them in a text file requirements.txt for easy install with command "pip install -r requirements.txt"
Thank you for your time!

D:\Bip39Generator\generate12words.py -n 50
  File "D:\Bip39Generator\generate12words.py", line 66
    except getopt.error, msg:
                       ^
SyntaxError: invalid syntax

**Comment by su314ka** [comment]
It`s working with python 2.7.12 but not with 3.7.2.

Is possible to remove the space before the first word and the last one in the generated txt file?
Thanks!
